### ISSUE TITLE
Authentication not possible

### ISSUE THREAD

**Issue by bebablub** [lorenzobenvenuti/strava-cli#1]
Hello,

i'm having problems with authentication (and your latest master). Steps to reproduce:
> python2 ./strava-cli.py authenticate -i <myclientid> -s <myclientsecret>

results in:
> Navigate to http://localhost:8080 using your web browser and perform the authorization flow.
> Press CTRL-C to abort
>  * Serving Flask app "auth" (lazy loading)
>  * Environment: production
>    WARNING: This is a development server. Do not use it in a production deployment.
>    Use a production WSGI server instead.
>  * Debug mode: off

So far so good. After browsing to:
> http://localhost:8080

i'm redirected to:
> https://www.strava.com/oauth/authorize?client_id=<myclientid>&response_type=code&redirect_uri=http://localhost:8080/token&scope=view_private,write

which says
> {"message":"Bad Request","errors":[{"resource":"Authorize","field":"scope","code":"invalid"}]}

I'm pretty sure it has something todo with:
https://developers.strava.com/docs/authentication/#refreshingexpiredaccesstokens
https://developers.strava.com/docs/oauth-updates/
Strava disabled all livetime access tokens this week. 

Is it possible to update your script to work with the new OAuth flow and refresh tokens?

Thank you very much for your work!

Best regards!

**Comment by lorenzobenvenuti** [comment]
Hi, I implemented a quick fix in branch `tokens`; code needs some refactoring before it can be merged into `master`, but it should work.

Thanks!

lorenzo

**Comment by bebablub** [comment]
Hi!
checked out your branch and it seems to fix the auth issues. Thank you very much for the help and fast reaction :)

Best regards!

**Comment by lorenzobenvenuti** [comment]
Merged to master.
