### ISSUE TITLE
Last activity is doubled

### ISSUE THREAD

**Issue by bubendorf** [lorenzobenvenuti/strava-cli#11]
Everytime I do a "strava-cli.py activities" the last activity is doubled.
i.E after some "strava-cli.py activities --filter after=20210506"
5254807928      EBikeRide       2021-05-07T05:38:49     Fahrt am Morgen 5943    56160.9 491.4
5254807928      EBikeRide       2021-05-07T05:38:49     Fahrt am Morgen 5943    56160.9 491.4
5254807928      EBikeRide       2021-05-07T05:38:49     Fahrt am Morgen 5943    56160.9 491.4
5251663196      Ride    2021-05-06T17:00:18     Fahrt am Nachmittag     731     4398.5  28.0
5251663196      Ride    2021-05-06T17:00:18     Fahrt am Nachmittag     731     4398.5  28.0
5249633139      Ride    2021-05-06T08:00:54     Fahrt am Morgen 757     4478.8  21.0
5249633139      Ride    2021-05-06T08:00:54     Fahrt am Morgen 757     4478.8  21.0

**Comment by lorenzobenvenuti** [comment]
Hi Markus, 

thanks for reporting this bug. I think I've found the issue, can you try to pull the latest changes, clear the cache (`strava-cli.py clear-cache`) and retry? 

Thanks,

lorenzo

**Comment by bubendorf** [comment]
Fixed!
Many thanks for this great tool and the quick fix.
Markus

**Comment by lorenzobenvenuti** [comment]
Thank you!
